### DISCUSSION TITLE
Exclude/change env vars set by `assume` "AWS_PROFILE"

### DISCUSSION THREAD

**Discussion by 1oglop1** [fwdcloudsec/granted#858] [Issue Triage]
Hi, 

I have a problem with `AWS_PROFILE` variable breaking my workflow.

I am deploying `eks cluster` with `pulumi` and `AWS_PROFILE` prevents the some k8s resources to be deployed.
With the error message

```
pulumi:pulumi:Stack (eks-cluster-):
    error: update failed
    error: eks:index:Cluster resource 'cluster' has a problem: grpc: the client connection is closing

    Error loading SSO Token: Token for org-sso does not exist
    Error loading SSO Token: Token for org-sso does not exist

  kubernetes:core/v1:ConfigMap (cluster-nodeAccess):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://1234.gr7.eu-central-1.eks.amazonaws.com/openapi/v2?timeout=32s": getting credentials: exec: executable aws failed with exit code 255
````

Turns out there are 2 workarounds:
1) setting the `--export-sso-token` -> `assume profile --export-sso-token` 
2) uset `AWS_PROFILE` variable

I noticed several other issues caused by AWS_PROFILE eg. #555 

It would be great if there were a place where I could decide which env vars are exported.

**Comment by chrnorm** [comment]
Are you using the [Granted EKS recipe](https://docs.commonfate.io/granted/recipes/eks) here? Can you please share your kubeconfig? (feel free to redact any ARNs). I think this may be caused by using the default EKS kubeconfig, rather than the modified kubeconfig as per our recipe.

**Reply by 1oglop1** [reply]
Whatever was it I "fixed" it by setting this `ExportSSOToken = true` - but I could not find out what it does.
Also, at the moment,t setting AWS_PROFILE together with other AWS_SECRETs

https://github.com/aws/aws-sdk-js-v3/blob/e4e386e53c3226ffefb03a997468ca5b8bfcd819/packages/credential-provider-node/src/defaultProvider.ts#L74-L87
```
@aws-sdk/credential-provider-node - defaultProvider::fromEnv WARNING:
        Multiple credential sources detected:
        Both AWS_PROFILE and the pair AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY static credentials are set.
        This SDK will proceed with the AWS_PROFILE value.
        However, a future version may change this behavior to prefer the ENV static credentials.
        Please ensure that your environment only sets either the AWS_PROFILE or the
        AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY pair.
```

What `assume` currently causes in kubeconfig is this
```
  - name: arn:aws:eks:eu-central-1:REDACTED:cluster/services
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - eu-central-1
          - eks
          - get-token
          - --cluster-name
          - services
          - --output
          - json
        command: aws
        env:
          - name: AWS_PROFILE
            value: some-aws-profile
  ```
  
  opposed to not setting `AWS_PROFILE`
  ```
    - name: arn:aws:eks:eu-central-1:REDACTED:cluster/services
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - eu-central-1
          - eks
          - get-token
          - --cluster-name
          - services
          - --output
          - json
        command: aws
```

My experience with AWS led me to avoid using `profile` altogether because the implementation lacks the simplicity of setting environment variables.

Also, we have several K8S clusters in multiple accounts, so modifying kubeconfig manually after the tools have been modified is a bit clunky. 

Right now, my workflow is 
```
ku() { aws eks update-kubeconfig --name $1; }

aws-vault <profile> exec 
ku <cluster name>

kubectl get pods
```
